library(Stat2Data)
#4.10
data(ReligionGDP)
logGDP=log(ReligionGDP$GDP)
plot(logGDP~ReligionGDP$Religiosity)
lm1=lm(logGDP~ReligionGDP$Religiosity)
summary(lm1)
ReligionGDP$EastEurope=as.factor(ReligionGDP$EastEurope)
ReligionGDP$MiddleEast=as.factor(ReligionGDP$MiddleEast)
ReligionGDP$Asia=as.factor(ReligionGDP$Asia)
ReligionGDP$WestEurope=as.factor(ReligionGDP$WestEurope)
ReligionGDP$Americas=as.factor(ReligionGDP$Americas)
lm2=lm(logGDP~Religiosity+EastEurope+MiddleEast+Asia+WestEurope+Americas, data=ReligionGDP)
summary(lm2)
anova (lm2, lm1)

#2
data(BaseballTimes)
pairs(~Time+Runs+Margin+Pitchers+Attendance, data = BaseballTimes)
lm3=lm(Time~Runs+Margin+Pitchers+Attendance, data=BaseballTimes)
lm4=lm(Time~Runs+Pithcers, data=BaseballTimes)
summary(lm3)
summary(lm4)
anova(lm4,lm3)

library(leaps)
library(car)
par(mfrow=c(1,1))
subsets(forwardTime)